# -*- coding: utf-8 -*-
"""proyectoferreteriaversion2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZLsIDjzTHn_S4QNeMJ-xaQK42B4-MWxg
"""

from datetime import datetime


# CLASE BASE PERSONA

class Persona:

    def __init__(self, nombre, correo, direccion, telefono):
        self._nombre = nombre
        self._correo = correo
        self._direccion = direccion
        self._telefono = telefono

    def mostrar_info(self):
        print(f"Nombre: {self._nombre}")
        print(f"Correo: {self._correo}")
        print(f"Dirección: {self._direccion}")
        print(f"Teléfono: {self._telefono}")



# CLASE CLIENTE (HEREDA)


class Cliente(Persona):

    def __init__(self, id_cliente, nombre, correo, direccion, telefono, rfc):
        super().__init__(nombre, correo, direccion, telefono)
        self.__id_cliente = id_cliente
        self.__rfc = rfc

    def id(self):
        return self.__id_cliente

    def mostrar_info(self):
        print(f"ID Cliente: {self.__id_cliente}")
        super().mostrar_info()
        print(f"RFC: {self.__rfc}")
        print("-" * 30)


# CLASE EMPLEADO (HEREDA)


class Empleado(Persona):

    def __init__(self, nombre, correo, direccion, telefono, id_empleado, departamento, usuario, contrasena):
        super().__init__(nombre, correo, direccion, telefono)
        self.__id_empleado = id_empleado
        self.__departamento = departamento
        self.__usuario = usuario
        self.__contrasena = contrasena

    def usuario(self):
        return self.__usuario

    def contrasena(self):
        return self.__contrasena

    def mostrar_info(self):
        print(f"Empleado ID: {self.__id_empleado}")
        super().mostrar_info()
        print(f"Departamento: {self.__departamento}")
        print("-" * 30)


# CLASE PRODUCTO


class Producto:

    def __init__(self, codigo, nombre, categoria, precio_unitario):
        self.__codigo = codigo
        self.__nombre = nombre
        self.__categoria = categoria
        self.__precio_unitario = precio_unitario

    def codigo(self):
        return self.__codigo

    def nombre(self):
        return self.__nombre

    def precio(self):
        return self.__precio_unitario

    def mostrar_info(self):
        print(f"Codigo: {self.__codigo}")
        print(f"Nombre: {self.__nombre}")
        print(f"Categoria: {self.__categoria}")
        print(f"Precio: {self.__precio_unitario}")


# INVENTARIO

class Inventario_producto:

    def __init__(self, producto, cantidad):
        self.__producto = producto
        self.__cantidad = cantidad
        self.__vendidos = 0

    def disponibles(self):
        return self.__cantidad - self.__vendidos

    def vender(self, cantidad):
        if cantidad <= self.disponibles():
            self.__vendidos += cantidad
            return True
        return False

    def agregar_stock(self, cantidad):
        self.__cantidad += cantidad

    def producto(self):
        return self.__producto

    def mostrar_estado(self):
        self.__producto.mostrar_info()
        print(f"Stock total: {self.__cantidad}")
        print(f"Vendidos: {self.__vendidos}")
        print(f"Disponibles: {self.disponibles()}")
        print("-" * 30)


# VENTA

class Venta:

    def __init__(self, folio, id_cliente, codigo_producto, cantidad, total):
        self.__folio = folio
        self.__id_cliente = id_cliente
        self.__codigo_producto = codigo_producto
        self.__fecha = datetime.now().strftime("%Y-%m-%d %H:%M")
        self.__cantidad = cantidad
        self.__total = total

    def mostrar_info(self):
        print(f"Folio: {self.__folio}")
        print(f"Cliente ID: {self.__id_cliente}")
        print(f"Producto Código: {self.__codigo_producto}")
        print(f"Cantidad: {self.__cantidad}")
        print(f"Total: ${self.__total:.2f}")
        print(f"Fecha: {self.__fecha}")
        print("-" * 30)


# CLASE FERRETERIA

class Ferreteria:

    def __init__(self):

        self.productos = []
        self.clientes = []
        self.ventas = []
        self.empleados = []

        self.folio_actual = 1

        # EMPLEADO ADMIN POR DEFECTO
        admin = Empleado(
            "Administrador",
            "admin@ferreteria.com",
            "Oficina",
            "0000000000",
            "E001",
            "Administración",
            "admin",
            "1234"
        )

        self.empleados.append(admin)


    # LOGIN


    def login(self):

        while True:

            print("\n===== LOGIN EMPLEADO =====")

            usuario = input("Usuario: ")
            contrasena = input("Contraseña: ")

            for e in self.empleados:

                if e.usuario() == usuario and e.contrasena() == contrasena:
                    print("\nBienvenido al sistema\n")
                    return True

            print("Credenciales incorrectas")

    # BUSCAR

    def buscar_producto(self, codigo):

        for item in self.productos:
            if item.producto().codigo() == codigo:
                return item

        return None


    def buscar_cliente(self, id_cliente):

        for c in self.clientes:
            if c.id() == id_cliente:
                return c

        return None


    # MENU

    def menu(self):

        while True:

            print("\n===== SISTEMA FERRETERÍA =====")
            print("1. Dar de alta producto")
            print("2. Mostrar inventario")
            print("3. Consultar producto")
            print("4. Registrar cliente")
            print("5. Consultar cliente")
            print("6. Mostrar clientes")
            print("7. Registrar venta")
            print("8. Historial ventas")
            print("9. Cerrar sesión")

            opcion = input("Seleccione: ")

            if opcion == "1":

                codigo = input("Código: ")
                nombre = input("Nombre: ")
                categoria = input("Categoría: ")
                precio = float(input("Precio: "))
                cantidad = int(input("Cantidad: "))

                producto = Producto(codigo, nombre, categoria, precio)
                inventario = Inventario_producto(producto, cantidad)

                self.productos.append(inventario)

                print("Producto registrado")


            elif opcion == "2":

                for p in self.productos:
                    p.mostrar_estado()


            elif opcion == "3":

                codigo = input("Código producto: ")

                producto = self.buscar_producto(codigo)

                if producto:
                    producto.mostrar_estado()
                else:
                    print("Producto no encontrado")


            elif opcion == "4":

                id_cliente = input("ID cliente: ")
                nombre = input("Nombre: ")
                correo = input("Correo: ")
                direccion = input("Dirección: ")
                telefono = input("Teléfono: ")
                rfc = input("RFC: ")

                cliente = Cliente(id_cliente, nombre, correo, direccion, telefono, rfc)

                self.clientes.append(cliente)

                print("Cliente registrado")


            elif opcion == "5":

                id_cliente = input("ID cliente: ")

                cliente = self.buscar_cliente(id_cliente)

                if cliente:
                    cliente.mostrar_info()
                else:
                    print("Cliente no encontrado")


            elif opcion == "6":

                for c in self.clientes:
                    c.mostrar_info()


            elif opcion == "7":

                codigo = input("Código producto: ")

                producto = self.buscar_producto(codigo)

                if producto is None:
                    print("Producto no encontrado")
                    continue

                id_cliente = input("ID cliente (999999 público general): ")
                cantidad = int(input("Cantidad: "))

                if producto.vender(cantidad):

                    total = cantidad * producto.producto().precio()

                    venta = Venta(
                        self.folio_actual,
                        id_cliente,
                        codigo,
                        cantidad,
                        total
                    )

                    self.ventas.append(venta)
                    self.folio_actual += 1

                    print("Venta registrada")
                    venta.mostrar_info()

                else:
                    print("Inventario insuficiente")


            elif opcion == "8":

                for v in self.ventas:
                    v.mostrar_info()


            elif opcion == "9":

                print("Cerrando sesión...")
                break

            else:
                print("Opción inválida")


# EJECUCIÓN

sistema = Ferreteria()

while True:

    if sistema.login():
        sistema.menu()

    salir = input("¿Desea cerrar el programa? (s/n): ")

    if salir.lower() == "s":
        print("Programa finalizado")
        break